### PR TITLE
Updated for V10: data property deprecation and layer handling

### PR DESCRIPTION
**Pull request by IHaveThatPower**
Made a fairly simple update to various parts of the module that were referencing `data` properties, which are deprecated in Foundry V10. Also tweaked the `layerGetElement` function so that it iterates over the layers as Foundry V10 understands them.

### CODE REVIEW

**Comment by OsiJr** [comment]
I've been testing this- for many use cases it's working great. There was an issue in some places when accessing elements from the V9 tiles foreground layer. Removing the references to `canvas.foreground` does seem to work. I have opened a PR to your branch @IHaveThatPower with this change.

**Comment by IHaveThatPower** [comment]
Merged in your request!

**Comment by KayelGee** [comment]
I just saw this PR. I've already been working on the v10 compatibility and the deprecation warnings myself so I'm not going to check if this PR works or not but once I'm finished fixing all the issues on my local copy I'll check if I missed anything that's in this PR.

**Comment by KayelGee** [comment]
I checked the differences between master and this PR and they are minor(besides some missing documents in your version).

I've left the foreground code in just in case I'll need it, but I'll probably remove it in v11.

LayerGetElement was also just a wrapper to get a tile in the foreground layer the same way. The layer of an element is always known, expect that tiles always returned background in v9 so that's why this exists. I'll remove the foreground code here aswell in v11.

**Pull request closed without merging**
